### ISSUE TITLE
Convert intersections to place objects with nodes.

### ISSUE THREAD

**Issue by djohns451** [MicroGSD/RoadArchitect#22]

**Comment by gsdnano** [comment]
My ideas for updating the intersections was to implement a less dynamic but more pluggable system, never got around to it though.

Quite a bit of the code complexity in the RA code base revolves around the creation of dynamic intersections.

Possibly converting intersections to their own placeable objects with node "connection points" that the RA road would hook into and adjust its tangent appropriately. This would reduce code complexity significantly and allow users to plug in their own intersections, on top of whatever base models would be provided.

This system would also allow editor placement of exits / onramps / parking lots to existing road systems. Where the connection type would be 'pass-through' rather than 'intersection' in the code base.

I think a system like that would allow quite a few possibilities that the current system doesn't.

**Comment by MCrafterzz** [comment]
Have you started implemented that?
