### ISSUE TITLE
Arch bridge unit test produces erroneous output with Unity 5.6.0f3

### ISSUE THREAD

**Issue by djohns451** [MicroGSD/RoadArchitect#5]
![image](https://cloud.githubusercontent.com/assets/17502055/25809055/eaeb966a-33d9-11e7-9bcc-5c88745e1cf6.png)

**Comment by djohns451** [comment]
Rerunning the unit test fixes terrain issue, scaling issue persists,
![image](https://cloud.githubusercontent.com/assets/17502055/25809190/4b26e228-33da-11e7-92cb-7681f36f9351.png)

**Comment by TomOR1** [comment]
elaborate but try the unitypackage if you haven't already:

https://github.com/MicroGSD/RoadArchitect/releases

**Comment by djohns451** [comment]
@TomOR1 In fact, this is the output from the unitypackage.

**Comment by TomOR1** [comment]
@djohns415, could you possibly explain what your problem is, specifically?? 

If you're problem is with the jerkyness of the terrain then look for a setting called 'terrain smoothness' or something like that. I haven't used road architect for a while so ill find the name of the setting. 

If your problem isn't with this above then I request you spend 5-10 minutes writing out what your problem is so I can try to fix the problem. Alternatively you could annotate screen shots using the windows snip tool (included in Windows 7 and beyond i think)  or you could voice over a screen recording using Open Broadcaster Software (free to download / use) 


If none of the above options are viable then i suggest you play around with all the settings, I find it the best way to learn things
