### ISSUE TITLE
How to Change the Lane Width of the Road?

### ISSUE THREAD

**Issue by johnny77lee** [MicroGSD/RoadArchitect#68]
Hi ,

In the RoadArchitect ， Default Lane width is 5M of the Road .
But in the Inspector of Road，when I change the "Lane Width" to other Value (ex. 8M )  in Road options ，
I couldn't found any change of the Road .
If I press the icon like "enter" in the Road options , the value of Lane width will return 5 M .

So......Would you provide the rule about "How to Change the Lane Width of the Road ? "

Thanks

**Comment by embeddedt** [comment]
@johnny77lee Try changing the value to 8 meters and then clicking on another textbox. The "enter" icon actually means "reset to default value".

**Comment by FritzsHero** [comment]
This Issue was already answered by embeddedt; I do want to add some Lines to this.

You can change the Road width by changing the "Lane width" to the desired value and then clicking onto another check box. The Road then should automatically update itself. You could also enter the value into the field and manually press the "Update Road" Button. 

I hope this answered your question.
This answer closes this Issue.
Feel free to reopen this Issue, if you have further questions regarding the Lane width.
You can also open new Tickets for other Questions.

Best Regards
