### ISSUE TITLE
default settings

### ISSUE THREAD

**Issue by yahya858** [MicroGSD/RoadArchitect#71]
hi ı open package and default setting not  there and bridges start ,end doesn't exist .I tried unity version 2019.1.9f1 and 2018.1.9f2 it is same on both can you help me
![Ekran Alıntısı7](https://user-images.githubusercontent.com/49416110/61326231-fa19f080-a81e-11e9-8b4f-69ea6e5eb076.PNG)
![Ekran Alıntısı](https://user-images.githubusercontent.com/49416110/61326232-fa19f080-a81e-11e9-8efd-a44b3149b8f8.PNG)
![Ekran Alıntısı2](https://user-images.githubusercontent.com/49416110/61326234-fab28700-a81e-11e9-96c8-a8a0f31e7025.PNG)
![Ekran Alıntısı4](https://user-images.githubusercontent.com/49416110/61326235-fab28700-a81e-11e9-8317-018c6ce84c03.PNG)
![Ekran Alıntısı5](https://user-images.githubusercontent.com/49416110/61326236-fab28700-a81e-11e9-914c-ac22103e3e90.PNG)
![Ekran Alıntısı6](https://user-images.githubusercontent.com/49416110/61326237-fab28700-a81e-11e9-9322-07c94caa8d43.PNG)

**Comment by embeddedt** [comment]
First off, I would recommend using FritzsHero's fork. It has several bug fixes and a few other features.

Second, the base folder needs to be named just `RoadArchitect` (and nothing else).

Hope that helps.

**Comment by FritzsHero** [comment]
Sorry for taking ages to reply.
The main problem you are facing is that the RoadArchitect folder in your project is named RoadArchitect-1.7 instead of just RoadArchitect .
This seems to be a problem by the unitypackage, I might republish a fixed 1.7 version.

As embeddedt already stated there is a more up to date version available on his fork and my fork.
If you need RoadArchitect in a stable state, I would recommend 1.7 / 1.8 or 1.9.
If you like a experimental version you can also use my fork (wip 2.0), but it might not be fully compatible with prior version.

**Comment by yahya858** [comment]
thank you problem solved
